#pragma once

#define PULSE_STOP_THREAD _PULSE_CODE_MINAVAIL + 1
#define PULSE_INTR_ON_PORT0 _PULSE_CODE_MINAVAIL + 2
#define PULSE_INTR_ON_PORT0_MACHINE1 _PULSE_CODE_MINAVAIL + 3
#define PULSE_INTR_ON_PORT0_MACHINE2 _PULSE_CODE_MINAVAIL + 4
#define PULSE_LOW_HIGH_MACHINE1 _PULSE_CODE_MINAVAIL + 5
#define PULSE_HIGH_LOW_MACHINE1 _PULSE_CODE_MINAVAIL + 6
#define PULSE_LOW_HIGH_MACHINE2 _PULSE_CODE_MINAVAIL + 7
#define PULSE_HIGH_LOW_MACHINE2 _PULSE_CODE_MINAVAIL + 8

