#pragma once

#define PULSE_STOP_THREAD                 	_PULSE_CODE_MINAVAIL + 1
#define PULSE_INTRRUPT                 	   	_PULSE_CODE_MINAVAIL + 2
#define PULSE_GPIO                    	    _PULSE_CODE_MINAVAIL + 3

#define PULSE_LOW_HIGH_MACHINE1           	_PULSE_CODE_MINAVAIL + 5
#define PULSE_HIGH_LOW_MACHINE1           	_PULSE_CODE_MINAVAIL + 6
#define PULSE_LOW_HIGH_MACHINE2        		_PULSE_CODE_MINAVAIL + 7
#define PULSE_HIGH_LOW_MACHINE2           	_PULSE_CODE_MINAVAIL + 8

#define PULSE_HIGHT                      	_PULSE_CODE_MINAVAIL + 9

#define PULSE_FROM_FSM_TO_HAL           	_PULSE_CODE_MINAVAIL + 10 // TODO: not used yet

//Timer Codes
#define PULSE_TIME_OUT_MIN_LBB_TO_HS				_PULSE_CODE_MINAVAIL + 12
#define PULSE_TIME_OUT_MAX_LBB_TO_HS				_PULSE_CODE_MINAVAIL + 13
#define PULSE_TIME_OUT_MIN_HS_TO_LBS				_PULSE_CODE_MINAVAIL + 14
#define PULSE_TIME_OUT_MAX_HS_TO_LBS				_PULSE_CODE_MINAVAIL + 15
#define PULSE_TIME_OUT_MIN_LBS_TO_LBE				_PULSE_CODE_MINAVAIL + 16
#define PULSE_TIME_OUT_MAX_LBS_TO_LBE				_PULSE_CODE_MINAVAIL + 17
#define PULSE_TIME_OUT_MIN_LBE_TO_LBA				_PULSE_CODE_MINAVAIL + 18
#define PULSE_TIME_OUT_MAX_LBE_TO_LBA				_PULSE_CODE_MINAVAIL + 19

// PULSE FLASH
#define PULSE_TIME_OUT_FLASH    					_PULSE_CODE_MINAVAIL + 20
#define PULSE_FLASH_ON							_PULSE_CODE_MINAVAIL + 21
#define PULSE_FLASH_OFF							_PULSE_CODE_MINAVAIL + 22
